In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from google.colab import files
uploaded = files.upload()

Saving diabetes_dataset__2019.csv to diabetes_dataset__2019.csv


In [46]:
train = pd.read_csv('/content/diabetes_dataset__2019.csv')

In [47]:
train.head()

Age Gender Family_Diabetes highBP      PhysicallyActive   BMI Smoking  \
0  50-59   Male              no    yes        one hr or more  39.0      no   
1  50-59   Male              no    yes  less than half an hr  28.0      no   
2  40-49   Male              no     no        one hr or more  24.0      no   
3  50-59   Male              no     no        one hr or more  23.0      no   
4  40-49   Male              no     no  less than half an hr  27.0      no   

  Alcohol  Sleep  SoundSleep RegularMedicine      JunkFood     Stress BPLevel  \
0      no      8           6              no  occasionally  sometimes    high   
1      no      8           6             yes    very often  sometimes  normal   
2      no      6           6              no  occasionally  sometimes  normal   
3      no      8           6              no  occasionally  sometimes  normal   
4      no      8           8              no  occasionally  sometimes  normal   

   Pregancies Pdiabetes UriationFreq Diabetic  
0         0.0         0     not much       no  
1         0.0         0     not much       no  
2         0.0         0     not much       no  
3         0.0         0     not much       no  
4         0.0         0     not much       no

In [39]:
print(train.shape)
print("________________________________________")
print(train.isna().sum())

(952, 18)
________________________________________
Age                  0
Gender               0
Family_Diabetes      0
highBP               0
PhysicallyActive     0
BMI                  4
Smoking              0
Alcohol              0
Sleep                0
SoundSleep           0
RegularMedicine      0
JunkFood             0
Stress               0
BPLevel              0
Pregancies          42
Pdiabetes            1
UriationFreq         0
Diabetic             1
dtype: int64


In [48]:
#Так как пропусков не так много, то можно всех их удалить
train = train.dropna()

In [41]:
print("________________________________________")
print(train.isna().sum())

________________________________________
Age                 0
Gender              0
Family_Diabetes     0
highBP              0
PhysicallyActive    0
BMI                 0
Smoking             0
Alcohol             0
Sleep               0
SoundSleep          0
RegularMedicine     0
JunkFood            0
Stress              0
BPLevel             0
Pregancies          0
Pdiabetes           0
UriationFreq        0
Diabetic            0
dtype: int64


In [42]:
print(train['Age'].unique())
print(train['PhysicallyActive'].unique())
print(train['JunkFood'].unique())
print(train['Stress'].unique())
print(train['BPLevel'].unique())

['50-59' '40-49' 'less than 40' '60 or older']
['one hr or more' 'less than half an hr' 'none' 'more than half an hr']
['occasionally' 'very often' 'often' 'always']
['sometimes' 'not at all' 'very often' 'always']
['high' 'normal' 'low' 'Low' 'High' 'normal ']


In [65]:
train.loc[train["Age"]=='less than 40' , 'Age'] = 1
train.loc[train["Age"]=='40-49' , 'Age'] = 2
train.loc[train["Age"]=='50-59' , 'Age'] = 3
train.loc[train["Age"]=='60 or older' , 'Age'] = 4

train.loc[train['PhysicallyActive']=='none' , 'PhysicallyActive'] = 1
train.loc[train['PhysicallyActive']=='less than half an hr' , 'PhysicallyActive'] = 2
train.loc[train['PhysicallyActive']=='more than half an hr' , 'PhysicallyActive'] = 3
train.loc[train['PhysicallyActive']=='one hr or more' , 'PhysicallyActive'] = 4

train.loc[train['JunkFood']=='occasionally' , 'JunkFood'] = 1
train.loc[train['JunkFood']=='often' , 'JunkFood'] = 2
train.loc[train['JunkFood']=='very often' , 'JunkFood'] = 3
train.loc[train['JunkFood']=='always' , 'JunkFood'] = 4

train.loc[train['Stress']=='not at all' , 'Stress'] = 1
train.loc[train['Stress']=='sometimes' , 'Stress'] = 2
train.loc[train['Stress']=='very often' , 'Stress'] = 3
train.loc[train['Stress']=='always' , 'Stress'] = 4

train.loc[train['BPLevel']=='Low' , 'BPLevel'] = 1
train.loc[train['BPLevel']=='low' , 'BPLevel'] = 1
train.loc[train['BPLevel']=='normal' , 'BPLevel'] = 2
train.loc[train['BPLevel']=='normal ' , 'BPLevel'] = 2
train.loc[train['BPLevel']=='high' , 'BPLevel'] = 3
train.loc[train['BPLevel']=='High' , 'BPLevel'] = 3

train.loc[train['Family_Diabetes']=='no' , 'Family_Diabetes'] = 0
train.loc[train['Family_Diabetes'] !=0 , 'Family_Diabetes'] = 1

train.loc[train['Gender']=='Male' , 'Gender'] = 0
train.loc[train['Gender'] !=0 , 'Gender'] = 1

train.loc[train['highBP']=='no' , 'highBP'] = 0
train.loc[train['highBP'] !=0 , 'highBP'] = 1

train.loc[train['Smoking']=='no' , 'Smoking'] = 0
train.loc[train['Smoking'] !=0 , 'Smoking'] = 1

train.loc[train['Smoking']=='no' , 'Smoking'] = 0
train.loc[train['Smoking'] !=0 , 'Smoking'] = 1

train.loc[train['Alcohol']=='no' , 'Alcohol'] = 0
train.loc[train['Alcohol'] !=0 , 'Alcohol'] = 1

train.loc[train['RegularMedicine']=='no' , 'RegularMedicine'] = 0
train.loc[train['RegularMedicine'] !=0 , 'RegularMedicine'] = 1

train.loc[train['Diabetic']=='no' , 'Diabetic'] = 0
train.loc[train['Diabetic'] !=0 , 'Diabetic'] = 1

train.loc[train['UriationFreq']=='not much' , 'UriationFreq'] = 0
train.loc[train['UriationFreq'] !=0 , 'UriationFreq'] = 1

train.loc[train['Pdiabetes']=='yes' , 'Pdiabetes'] = 1
train.loc[train['Pdiabetes']=='0' , 'Pdiabetes'] = 0



In [68]:
train = train.astype(int)

In [59]:
train.head()

Age Gender Family_Diabetes highBP PhysicallyActive   BMI Smoking Alcohol  \
0   3      0               0      1                4  39.0       0       0   
1   3      0               0      1                2  28.0       0       0   
2   2      0               0      0                4  24.0       0       0   
3   3      0               0      0                4  23.0       0       0   
4   2      0               0      0                2  27.0       0       0   

   Sleep  SoundSleep RegularMedicine JunkFood Stress BPLevel  Pregancies  \
0      8           6               0        1      2       3         0.0   
1      8           6               1        3      2       2         0.0   
2      6           6               0        1      2       2         0.0   
3      8           6               0        1      2       2         0.0   
4      8           8               0        1      2       2         0.0   

  Pdiabetes UriationFreq Diabetic  
0         0            0        0  
1         0            0        0  
2         0            0        0  
3         0            0        0  
4         0            0        0

In [62]:
for i in train.columns:
  print(train[i].unique())

[3 2 1 4]
[0 1]
[0 1]
[1 0]
[4 2 1 3]
[39. 28. 24. 23. 27. 21. 20. 26. 22. 15. 34. 30. 29. 18. 32. 31. 36. 38.
 40. 35. 19. 33. 17. 25. 42. 45.]
[0 1]
[0 1]
[ 8  6 10  7 11  9  4  5]
[ 6  8 10  7 11  4  9  5  3  2  1  0]
[0 1]
[1 3 2 4]
[2 1 3 4]
[3 2 1]
[0. 1. 2. 3. 4.]
[0 1]
[0 1]
[0 1]


In [69]:
from sklearn.model_selection import train_test_split

X = train.drop(['Diabetic'], axis=1)
y = train['Diabetic']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
model = LogisticRegression()
model.fit(X_train, y_train)
answers_pred = model.predict(X_test)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [76]:
model.coef_
#Меньше всего влияют BMI, Sleep,Stress и UriationFreq. А больше всего Age, Family_Diabetes, RegularMedicine и Pdiabetes

array([[ 1.03235892, -0.36361231,  1.27714556, -0.1918425 ,  0.1603991 ,
         0.01024342,  0.45552766,  0.1117809 , -0.05586965,  0.1603297 ,
         2.39494896,  0.30411608, -0.02065729,  0.39654818,  0.23112935,
         3.16637705, -0.00476547]])

In [77]:
a = model.coef_
c = train.columns
print('y =', round(model.intercept_[0], 3), end = '')
for i in range(17):
  print('+(', round(a[0][i], 3), ')*',c[i],sep ='', end =''  )

y = -7.521+(1.032)*Age+(-0.364)*Gender+(1.277)*Family_Diabetes+(-0.192)*highBP+(0.16)*PhysicallyActive+(0.01)*BMI+(0.456)*Smoking+(0.112)*Alcohol+(-0.056)*Sleep+(0.16)*SoundSleep+(2.395)*RegularMedicine+(0.304)*JunkFood+(-0.021)*Stress+(0.397)*BPLevel+(0.231)*Pregancies+(3.166)*Pdiabetes+(-0.005)*UriationFreq

In [81]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

tn, fp, fn, tp = confusion_matrix(y_test, answers_pred).ravel()
Accuracy = (tn+tp)/(tp+tn+fp+fn)
Recall = (tp)/(tp+fn)
Precision = (tp)/(tp+fp)

print('Accuracy =', Accuracy)
print('Recall =', Recall)
print('Precision =', Precision)
print('f1 =', 2*Recall*Precision/(Recall+Precision))

Accuracy = 0.8602941176470589
Recall = 0.7865168539325843
Precision = 0.7865168539325843
f1 = 0.7865168539325842


In [82]:
print(accuracy_score(y_test, answers_pred))
print(recall_score(y_test, answers_pred))
print(precision_score(y_test, answers_pred))
print(f1_score(y_test, answers_pred))

0.8602941176470589
0.7865168539325843
0.7865168539325843
0.7865168539325842
