# Задание

У каждого есть свой набор данный, который можно найти в ведомости на вкладке "Логистическая регрессия":

https://clck.ru/32BVWe

Скачиваете свой датасет с kaggle (для этого нужно авторизоваться с гугл аккаунт и скачать датасет).

**Ваша задача:**
1. Исследовать данные
2. Создать тренировочную и тестовую подвыборки
3. Построить модель логистической регрессии по своему набору данных (т.е. создать модель и обучить ее на тренировочной выборке)
4. Получить коэффиценты уравнения логистической регрессии (т.е. уравнение разделяющей поверхности). Сделать вывод какие из признаков оказались наиболее значимыми, какие нет и почему
5. Написать уравнение логистической регрессии.
6. Вывести confusion matrix для получившейся модели.
7. Вручную посчитать метрики: accuracy, recall, precision. f1.
8. Посчитать метрики с помощью библиотеки sklearn и сравнить с оценками из п.7.
9. Сделать письменный вывод получившихся результатов (хорошие или плохие получлись метрики и почему).

ВСЕ графики должны быть подписанны.
Ваша задача получить метрики как можно лучше.

## пыталась понять(фактически все списано)

In [3]:
import pandas as pd
from sklearn.model_selection import df_test_split
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import OrdinalEncoder
from sklearn.linear_model import LogisticRegression

In [5]:
from google.colab import files
upload = files.upload()
     

Saving lsdd.csv to lsdd.csv


In [145]:
import io
import pandas as pd
pf = pd.read_csv(io.BytesIO(upload['lsdd.csv']))
df = pf[["lumpy","dominant_land_cover"]]
df.columns = ["lumpy","dominant_land_cover"]
df

lumpy  dominant_land_cover
0          1                    2
1          1                    2
2          1                    2
3          1                    2
4          1                    3
...      ...                  ...
24798      0                    3
24799      0                    4
24800      0                    5
24801      0                    3
24802      0                    3

[24803 rows x 2 columns]

In [137]:
df = pd.read_csv("lsdd.csv")
df.head(10)

x          y region     country reportingDate   cld   dtr    frs  \
0  90.380931  22.437184   Asia  Bangladesh     10/9/2020  41.6  12.8   0.00   
1  87.854975  22.986757   Asia       India    20/12/2019  40.5  13.3   0.00   
2  85.279935  23.610181   Asia       India    20/12/2019  27.3  13.6   0.08   
3  81.564510  43.882221   Asia       China    25/10/2019  45.3  12.8  31.00   
4  81.161057  43.834976   Asia       China    25/10/2019  38.8  13.2  31.00   
5  81.248335  43.966008   Asia       China    25/10/2019  38.8  13.2  31.00   
6  81.074165  43.836019   Asia       China    25/10/2019  38.8  13.2  31.00   
7  81.547132  43.688309   Asia       China    25/10/2019  45.3  12.8  31.00   
8  81.239566  43.591386   Asia       China    25/10/2019  38.8  13.2  31.00   
9  81.324148  43.978094   Asia       China    25/10/2019  38.8  13.2  31.00   

   pet   pre   tmn   tmp   tmx   vap   wet  elevation  dominant_land_cover  \
0  2.3   1.7  12.7  19.1  25.5  15.7  0.00        147                    2   
1  2.4   0.0  13.2  19.8  26.5  16.3  0.00        145                    2   
2  2.3   0.6   9.4  16.2  23.0  13.0  0.98        158                    2   
3  0.4   8.8 -22.5 -16.1  -9.7   0.9  4.64        178                    2   
4  0.4  10.5 -20.4 -13.8  -7.2   1.2  1.69        185                    3   
5  0.4  10.5 -20.4 -13.8  -7.2   1.2  1.69        185                    3   
6  0.4  10.5 -20.4 -13.8  -7.2   1.2  1.69        185                    3   
7  0.4   8.8 -22.5 -16.1  -9.7   0.9  4.64        178                    2   
8  0.4  10.5 -20.4 -13.8  -7.2   1.2  1.69        185                    3   
9  0.4  10.5 -20.4 -13.8  -7.2   1.2  1.69        185                    3   

   X5_Ct_2010_Da  X5_Bf_2010_Da  lumpy  
0   27970.983100    3691.746950      1  
1   25063.646690     671.326701      1  
2    6038.477155    1426.839831      1  
3     760.703340       0.000000      1  
4     270.367426       0.000000      1  
5     270.367426       0.000000      1  
6     270.367426       0.000000      1  
7     760.703340       0.000000      1  
8     270.367426       0.000000      1  
9     270.367426       0.000000      1

In [146]:
print(df.shape)
print("________________________________________")
print(df.isna().sum())
     

(24803, 2)
________________________________________
lumpy                  0
dominant_land_cover    0
dtype: int64


In [144]:
from sklearn.model_selection import train_test_split
x=df.drop(columns=["x","lumpy"])
y=df["x"]
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3)
model = LogisticRegression()
model.fit(X_train, y_train)
pred = model.predict(X_test)

ValueError: ignored

In [147]:

df = df.dropna()

In [148]:
print("________________________________________")
print(df.isna().sum())

________________________________________
lumpy                  0
dominant_land_cover    0
dtype: int64


In [149]:
#print(df['region'].unique())
#print(df['y'].unique())
#print(df['pet'].unique())
print(df['dominant_land_cover'].unique())
print(df['lumpy'].unique())
  

[ 2  3  4  9  1  5 11  8 10  6  0  7]
[1 0]


In [150]:
df.loc[df["lumpy"]=='1' , 'lumpy'] = 0
df.loc[df["lumpy"]!=0 , 'lumpy'] = 1

df.loc[df["dominant_land_cover"]=='1' , 'dominant_land_cover'] = 1
df.loc[df["dominant_land_cover"]=='2' , 'dominant_land_cover'] = 2
df.loc[df["dominant_land_cover"]=='3' , 'dominant_land_cover'] = 3
df.loc[df["dominant_land_cover"]=='4' , 'dominant_land_cover'] = 4
df.loc[df["dominant_land_cover"]=='5' , 'dominant_land_cover'] = 5
df.loc[df["dominant_land_cover"]=='6' , 'dominant_land_cover'] = 6
df.loc[df["dominant_land_cover"]=='7' , 'dominant_land_cover'] = 7
df.loc[df["dominant_land_cover"]=='8' , 'dominant_land_cover'] = 8
df.loc[df["dominant_land_cover"]=='9' , 'dominant_land_cover'] = 9
df.loc[df["dominant_land_cover"]=='10' , 'dominant_land_cover'] = 10
df.loc[df["dominant_land_cover"]=='11' , 'dominant_land_cover'] = 11
df.loc[df["dominant_land_cover"]=='0' , 'dominant_land_cover'] = 0
df = df.astype(int)

In [151]:
df.head()

lumpy  dominant_land_cover
0      1                    2
1      1                    2
2      1                    2
3      1                    2
4      1                    3

In [152]:
for i in df.columns:
  print(df[i].unique())

[1 0]
[ 2  3  4  9  1  5 11  8 10  6  0  7]


In [153]:
from sklearn.model_selection import train_test_split

X = df.drop(['lumpy'], axis=1)
y = df['lumpy']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
model = LogisticRegression()
model.fit(X_train, y_train)
answers_pred = model.predict(X_test)

In [154]:
model.coef_

array([[-0.30259338]])

In [155]:
d = model.coef_
b = df.columns
print('y =', round(model.intercept_[0], 3), end = '')
for i in range(1):
  print('+(', round(d[0][i], 3), ')*',b[i],sep ='', end =''  )

y = -0.785+(-0.303)*lumpy

In [156]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

tn, fp, fn, tp = confusion_matrix(y_test, answers_pred).ravel()
Accuracy = (tn+tp)/(tp+tn+fp+fn)
Recall = (tp)/(tp+fn)
Precision = (tp)/(tp+fp)

print('Accuracy =', Accuracy)
print('Recall =', Recall)
print('Precision =', Precision)
print('f1 =', 2*Recall*Precision/(Recall+Precision))

Accuracy = 0.8791829055234511
Recall = 0.0
Precision = nan
f1 = nan


<ipython-input-156-7ea6d04732ef>:6: RuntimeWarning: invalid value encountered in long_scalars
  Precision = (tp)/(tp+fp)


In [157]:
print(accuracy_score(y_test, answers_pred))
print(recall_score(y_test, answers_pred))
print(precision_score(y_test, answers_pred))
print(f1_score(y_test, answers_pred))

0.8791829055234511
0.0
0.0
0.0


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
