In [ ]:
import pandas as pd
import numpy as np
from google.colab import files

test = files.upload()

Saving test.csv to test.csv


In [ ]:
train = files.upload()

Saving train.csv to train.csv


In [ ]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [ ]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [ ]:
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

In [ ]:
print(train.isna().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


In [ ]:
mean_class1 = train.groupby("Pclass").mean()['Age'].round().loc[1]
mean_class2 = train.groupby("Pclass").mean()['Age'].round().loc[2]
mean_class3 = train.groupby("Pclass").mean()['Age'].round().loc[3]
print(mean_class1, mean_class2, mean_class3)

train.loc[train["Pclass"]==1, 'Age'] = train.loc[train["Pclass"]==1, 'Age'].fillna(mean_class1)
train.loc[train["Pclass"]==2, 'Age'] = train.loc[train["Pclass"]==2, 'Age'].fillna(mean_class2)
train.loc[train["Pclass"]==3, 'Age'] = train.loc[train["Pclass"]==3, 'Age'].fillna(mean_class3)

print(train.isna().sum())

38.0 30.0 25.0
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


In [ ]:
train = train.drop(['Cabin'], axis=1)
print(train.isna().sum())
train = train.dropna()
print("___________После обработки всех пустых значений______________")
print(train.isna().sum())

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64
___________После обработки всех пустых значений______________
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64


In [ ]:
# Преобразуем категориальные признаки (Sex: male female) => Sex: 0 или 1
train = pd.get_dummies(train, columns=['Sex', 'Embarked'])
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name   Age  SibSp  Parch  \
0                              Braund, Mr. Owen Harris  22.0      1      0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0      1      0   
2                               Heikkinen, Miss. Laina  26.0      0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0      1      0   
4                             Allen, Mr. William Henry  35.0      0      0   
..                                                 ...   ...    ...    ...   
886                              Montvila, Rev. Juozas  27.0      0      0   
887                       Graham, Miss. Margaret Edith  19.0      0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  25.0      1      2   
889                              Behr, Mr. Karl Howell  26.0      0      0   
890                                Dooley, Mr. Patrick  32.0      0      0   

               Ticket     Fare  Sex_female  Sex_male  Embarked_C  Embarked_Q  \
0           A/5 21171   7.2500           0         1           0           0   
1            PC 17599  71.2833           1         0           1           0   
2    STON/O2. 3101282   7.9250           1         0           0           0   
3              113803  53.1000           1         0           0           0   
4              373450   8.0500           0         1           0           0   
..                ...      ...         ...       ...         ...         ...   
886            211536  13.0000           0         1           0           0   
887            112053  30.0000           1         0           0           0   
888        W./C. 6607  23.4500           1         0           0           0   
889            111369  30.0000           0         1           1           0   
890            370376   7.7500           0         1           0           1   

     Embarked_S  
0             1  
1             0  
2             1  
3             1  
4             1  
..          ...  
886           1  
887           1  
888           1  
889           0  
890           0  

[889 rows x 14 columns]

In [ ]:
train = train.drop(['Name', 'PassengerId', 'Ticket'], axis = 1)
train

Survived  Pclass   Age  SibSp  Parch     Fare  Sex_female  Sex_male  \
0           0       3  22.0      1      0   7.2500           0         1   
1           1       1  38.0      1      0  71.2833           1         0   
2           1       3  26.0      0      0   7.9250           1         0   
3           1       1  35.0      1      0  53.1000           1         0   
4           0       3  35.0      0      0   8.0500           0         1   
..        ...     ...   ...    ...    ...      ...         ...       ...   
886         0       2  27.0      0      0  13.0000           0         1   
887         1       1  19.0      0      0  30.0000           1         0   
888         0       3  25.0      1      2  23.4500           1         0   
889         1       1  26.0      0      0  30.0000           0         1   
890         0       3  32.0      0      0   7.7500           0         1   

     Embarked_C  Embarked_Q  Embarked_S  
0             0           0           1  
1             1           0           0  
2             0           0           1  
3             0           0           1  
4             0           0           1  
..          ...         ...         ...  
886           0           0           1  
887           0           0           1  
888           0           0           1  
889           1           0           0  
890           0           1           0  

[889 rows x 11 columns]

In [ ]:
from sklearn.model_selection import train_test_split

# Выделим вектор признаков Х и вектор ответов y
X = train.drop(['Survived'], axis=1)
y = train['Survived']

# train - на тренировочные и тестовые
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

model = LogisticRegression()
# model = KMeans()
# model = LinearRegression()

# модель учится, для этого ей нужны правильные
model.fit(X_train, y_train)

# тестируем, для признаков у которых нет ответов, мы предсказывает ответ
answers_pred = model.predict(X_test)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
model.coef_

array([[-1.15097980e+00, -3.56964605e-02, -2.94741253e-01,
        -6.38181361e-02,  2.32815868e-05,  2.21554801e+00,
        -3.68860060e-01,  6.55857730e-01,  7.70236481e-01,
         4.20593736e-01]])

In [ ]:
model.intercept_

array([2.1490754])

In [ ]:
from sklearn.metrics import accuracy_score

# Как оценить насколько хорошо работает ваша модель?

# answers_pred - ответы которые вернула модель для X_test
# y_test - это правильные ответы для X_test
print(accuracy_score(y_test,answers_pred))

0.8127340823970037


In [ ]:
test.loc[test['Pclass']==1,'Age'] = test.loc[test['Pclass']==1,'Age'].fillna(value=mean_class1)
test.loc[test['Pclass']==2,'Age'] = test.loc[test['Pclass']==2,'Age'].fillna(value=mean_class2)
test.loc[test['Pclass']==3,'Age'] = test.loc[test['Pclass']==3,'Age'].fillna(value=mean_class3)

# в тестовых есть одно пропущенное значение в колонке Fare - заменим его на среднее
test['Fare'] = test['Fare'].fillna(value=test['Fare'].mean())

# удалим столбец в котором много пропусков
test.drop('Cabin',axis=1,inplace=True)

# преобразуем категориальные признаки
test = pd.get_dummies(test, columns=['Sex', 'Embarked'])
print("Shape:", test.shape)

#удалим не нужные столбцы (не несут смысла для классификации)
test = test.drop(['Name','Ticket'],axis=1)

#выведем преобразованный датафремй
# head() - выводит первые пять строчек датафрейма
test.head()

Shape: (418, 13)


PassengerId  Pclass   Age  SibSp  Parch     Fare  Sex_female  Sex_male  \
0          892       3  34.5      0      0   7.8292           0         1   
1          893       3  47.0      1      0   7.0000           1         0   
2          894       2  62.0      0      0   9.6875           0         1   
3          895       3  27.0      0      0   8.6625           0         1   
4          896       3  22.0      1      1  12.2875           1         0   

   Embarked_C  Embarked_Q  Embarked_S  
0           0           1           0  
1           0           0           1  
2           0           1           0  
3           0           0           1  
4           0           0           1

In [ ]:
predictions = model.predict(test.drop(columns=['PassengerId']))
predictions

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [ ]:
final_prediction = pd.DataFrame({'PassengerId':test['PassengerId'],'Survived':predictions})

final_prediction.shape

final_prediction.to_csv('final_prediction.csv', index=False)
files.download("final_prediction.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
sub = files.upload()

Saving gender_submission.csv to gender_submission.csv


In [ ]:
sub = pd.read_csv("gender_submission.csv")

In [ ]:
sub.head()

PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [ ]:
final_prediction.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1