In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression

In [2]:
from google.colab import files 
uploaded = files.upload()

Saving test.csv to test.csv
Saving train.csv to train.csv


In [164]:
train = pd.read_csv("train.csv")

In [165]:
test = pd.read_csv("test.csv")

In [166]:
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [167]:
# размерность
print("train",train.shape)
print("test",test.shape)

train (891, 12)
test (418, 11)


In [168]:
print(train.info())
print(test.dtypes)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
PassengerId      int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked 

In [169]:
print("train: \n")
print(train.isna().sum())
print("\ntest: \n")
print(test.isna().sum())

train: 

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

test: 

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64


обработка train

In [170]:
train = train.drop(['Cabin'], axis=1)

In [171]:
mean_class1 = train.groupby("Pclass").mean()['Age'].round().loc[1]
mean_class2 = train.groupby("Pclass").mean()['Age'].round().loc[2]
mean_class3 = train.groupby("Pclass").mean()['Age'].round().loc[3]
print(mean_class1, mean_class2, mean_class3,'\n')
train.loc[train["Pclass"] == 1, 'Age'] = train.loc[train["Pclass"]==1, 'Age'].fillna(mean_class1)
train.loc[train["Pclass"] == 2, 'Age'] = train.loc[train["Pclass"]==2, 'Age'].fillna(mean_class2)
train.loc[train["Pclass"] == 3, 'Age'] = train.loc[train["Pclass"]==3, 'Age'].fillna(mean_class3)
train = train.dropna()
print(train.isna().sum())

38.0 30.0 25.0 

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64


In [172]:
train = pd.get_dummies(train, columns=['Sex', 'Embarked'])
train = train.drop(['Name', 'PassengerId', 'Ticket'], axis = 1)
train


Survived  Pclass   Age  SibSp  Parch     Fare  Sex_female  Sex_male  \
0           0       3  22.0      1      0   7.2500           0         1   
1           1       1  38.0      1      0  71.2833           1         0   
2           1       3  26.0      0      0   7.9250           1         0   
3           1       1  35.0      1      0  53.1000           1         0   
4           0       3  35.0      0      0   8.0500           0         1   
..        ...     ...   ...    ...    ...      ...         ...       ...   
886         0       2  27.0      0      0  13.0000           0         1   
887         1       1  19.0      0      0  30.0000           1         0   
888         0       3  25.0      1      2  23.4500           1         0   
889         1       1  26.0      0      0  30.0000           0         1   
890         0       3  32.0      0      0   7.7500           0         1   

     Embarked_C  Embarked_Q  Embarked_S  
0             0           0           1  
1             1           0           0  
2             0           0           1  
3             0           0           1  
4             0           0           1  
..          ...         ...         ...  
886           0           0           1  
887           0           0           1  
888           0           0           1  
889           1           0           0  
890           0           1           0  

[889 rows x 11 columns]

In [173]:
from sklearn.model_selection import train_test_split

X = train.drop(['Survived'], axis=1)
y = train['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

model = LogisticRegression()
model.fit(X_train, y_train)
answers_pred = model.predict(X_test)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [174]:
model.coef_


array([[-1.05143632, -0.03493804, -0.25314057, -0.19065016,  0.00398401,
         2.22221815, -0.53723596,  0.71702534,  0.52069258,  0.44726427]])

In [175]:
model.intercept_

array([1.94642548])

In [176]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,answers_pred))

0.7827715355805244


In [177]:
print(X_train.shape)
print(y_train.shape)

(622, 10)
(622,)


обработка test

In [178]:
test

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [179]:
print("\ntest: \n")
print(test.isna().sum())


test: 

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64


In [180]:
test = test.drop(['Cabin'], axis=1)

In [181]:
print("\ntest: \n")
print(test.isna().sum())


test: 

PassengerId     0
Pclass          0
Name            0
Sex             0
Age            86
SibSp           0
Parch           0
Ticket          0
Fare            1
Embarked        0
dtype: int64


In [182]:
test.loc[test['Pclass']==1,'Age'] = test.loc[test['Pclass']==1,'Age'].fillna(value=mean_class1)
test.loc[test['Pclass']==2,'Age'] = test.loc[test['Pclass']==2,'Age'].fillna(value=mean_class2)
test.loc[test['Pclass']==3,'Age'] = test.loc[test['Pclass']==3,'Age'].fillna(value=mean_class3)

test['Fare'] = test['Fare'].fillna(value=test['Fare'].mean())

test = pd.get_dummies(test, columns=['Sex', 'Embarked'])
print("Shape:", test.shape)
test = test.drop(['Name' , 'Ticket'],axis=1)

test

Shape: (418, 13)


PassengerId  Pclass   Age  SibSp  Parch      Fare  Sex_female  Sex_male  \
0            892       3  34.5      0      0    7.8292           0         1   
1            893       3  47.0      1      0    7.0000           1         0   
2            894       2  62.0      0      0    9.6875           0         1   
3            895       3  27.0      0      0    8.6625           0         1   
4            896       3  22.0      1      1   12.2875           1         0   
..           ...     ...   ...    ...    ...       ...         ...       ...   
413         1305       3  25.0      0      0    8.0500           0         1   
414         1306       1  39.0      0      0  108.9000           1         0   
415         1307       3  38.5      0      0    7.2500           0         1   
416         1308       3  25.0      0      0    8.0500           0         1   
417         1309       3  25.0      1      1   22.3583           0         1   

     Embarked_C  Embarked_Q  Embarked_S  
0             0           1           0  
1             0           0           1  
2             0           1           0  
3             0           0           1  
4             0           0           1  
..          ...         ...         ...  
413           0           0           1  
414           1           0           0  
415           0           0           1  
416           0           0           1  
417           1           0           0  

[418 rows x 11 columns]

In [183]:
predictions = model.predict(test.drop(columns=['PassengerId']))
predictions

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [184]:
final_prediction = pd.DataFrame({'PassengerId':test['PassengerId'],'Survived':predictions})
final_prediction.shape
final_prediction.to_csv('final_prediction.csv', index=False)
files.download("final_prediction.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [185]:
final_prediction

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]