In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression

In [87]:
train = pd.read_csv("https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_2/main/%D0%92%D0%B5%D1%81%D0%B5%D0%BD%D0%BD%D0%B8%D0%B9%20%D1%81%D0%B5%D0%BC%D0%B5%D1%81%D1%82%D1%80/class_work_2_log_reg/train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_2/main/%D0%92%D0%B5%D1%81%D0%B5%D0%BD%D0%BD%D0%B8%D0%B9%20%D1%81%D0%B5%D0%BC%D0%B5%D1%81%D1%82%D1%80/class_work_2_log_reg/test.csv")

In [88]:
print("________________________________________")
print(train.isna().sum())
print("________________________________________")
print(test.isna().sum())

________________________________________
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
________________________________________
PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64


In [89]:
mean_class1 = train.groupby("Pclass").mean()['Age'].round().loc[1]
mean_class2 = train.groupby("Pclass").mean()['Age'].round().loc[2]
mean_class3 = train.groupby("Pclass").mean()['Age'].round().loc[3]
print(mean_class1, mean_class2, mean_class3)
train.loc[train["Pclass"]==1, 'Age'] = train.loc[train["Pclass"]==1, 'Age'].fillna(mean_class1)
train.loc[train["Pclass"]==2, 'Age'] = train.loc[train["Pclass"]==2, 'Age'].fillna(mean_class2)
train.loc[train["Pclass"]==3, 'Age'] = train.loc[train["Pclass"]==3, 'Age'].fillna(mean_class3)
print(train.isna().sum())

38.0 30.0 25.0
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


In [90]:
train = train.drop(['Cabin'], axis=1)

In [91]:
train = train.dropna()

In [92]:
train = pd.get_dummies(train, columns=['Sex', 'Embarked'])
train = train.drop(['Name', 'PassengerId', 'Ticket'], axis = 1)
train

Survived  Pclass   Age  SibSp  Parch     Fare  Sex_female  Sex_male  \
0           0       3  22.0      1      0   7.2500           0         1   
1           1       1  38.0      1      0  71.2833           1         0   
2           1       3  26.0      0      0   7.9250           1         0   
3           1       1  35.0      1      0  53.1000           1         0   
4           0       3  35.0      0      0   8.0500           0         1   
..        ...     ...   ...    ...    ...      ...         ...       ...   
886         0       2  27.0      0      0  13.0000           0         1   
887         1       1  19.0      0      0  30.0000           1         0   
888         0       3  25.0      1      2  23.4500           1         0   
889         1       1  26.0      0      0  30.0000           0         1   
890         0       3  32.0      0      0   7.7500           0         1   

     Embarked_C  Embarked_Q  Embarked_S  
0             0           0           1  
1             1           0           0  
2             0           0           1  
3             0           0           1  
4             0           0           1  
..          ...         ...         ...  
886           0           0           1  
887           0           0           1  
888           0           0           1  
889           1           0           0  
890           0           1           0  

[889 rows x 11 columns]

In [93]:
from sklearn.model_selection import train_test_split
X = train.drop(['Survived'], axis=1)
y = train['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
model = LogisticRegression()
model.fit(X_train, y_train)
answers_pred = model.predict(X_test)


/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [94]:
model.coef_

array([[-0.93076759, -0.03551577, -0.39412242, -0.1678403 ,  0.00466128,
         2.1394977 , -0.57015421,  0.6543023 ,  0.55122602,  0.36381517]])

In [95]:
model.intercept_

array([1.94550965])

In [96]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,answers_pred))

0.797752808988764


In [97]:
print(X_train.shape)
print(y_train.shape)

(622, 10)
(622,)


In [98]:
mean_class1 = test.groupby("Pclass").mean()['Age'].round().loc[1]
mean_class2 = test.groupby("Pclass").mean()['Age'].round().loc[2]
mean_class3 = test.groupby("Pclass").mean()['Age'].round().loc[3]
print(mean_class1, mean_class2, mean_class3)
test.loc[test["Pclass"]==1, 'Age'] = test.loc[test["Pclass"]==1, 'Age'].fillna(mean_class1)
test.loc[test["Pclass"]==2, 'Age'] = test.loc[test["Pclass"]==2, 'Age'].fillna(mean_class2)
test.loc[test["Pclass"]==3, 'Age'] = test.loc[test["Pclass"]==3, 'Age'].fillna(mean_class3)
print(test.isna().sum())

41.0 29.0 24.0
PassengerId      0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64


In [99]:
test = test.drop(['Cabin'], axis=1)

In [100]:
value = test['Fare'].mean()
test['Fare'] = test['Fare'].fillna(value)

In [101]:
test = pd.get_dummies(test, columns=['Sex', 'Embarked'])
test = test.drop(['Name', 'PassengerId', 'Ticket'], axis = 1)
test

Pclass   Age  SibSp  Parch      Fare  Sex_female  Sex_male  Embarked_C  \
0         3  34.5      0      0    7.8292           0         1           0   
1         3  47.0      1      0    7.0000           1         0           0   
2         2  62.0      0      0    9.6875           0         1           0   
3         3  27.0      0      0    8.6625           0         1           0   
4         3  22.0      1      1   12.2875           1         0           0   
..      ...   ...    ...    ...       ...         ...       ...         ...   
413       3  24.0      0      0    8.0500           0         1           0   
414       1  39.0      0      0  108.9000           1         0           1   
415       3  38.5      0      0    7.2500           0         1           0   
416       3  24.0      0      0    8.0500           0         1           0   
417       3  24.0      1      1   22.3583           0         1           1   

     Embarked_Q  Embarked_S  
0             1           0  
1             0           1  
2             1           0  
3             0           1  
4             0           1  
..          ...         ...  
413           0           1  
414           0           0  
415           0           1  
416           0           1  
417           0           0  

[418 rows x 10 columns]

In [102]:
test

Pclass   Age  SibSp  Parch      Fare  Sex_female  Sex_male  Embarked_C  \
0         3  34.5      0      0    7.8292           0         1           0   
1         3  47.0      1      0    7.0000           1         0           0   
2         2  62.0      0      0    9.6875           0         1           0   
3         3  27.0      0      0    8.6625           0         1           0   
4         3  22.0      1      1   12.2875           1         0           0   
..      ...   ...    ...    ...       ...         ...       ...         ...   
413       3  24.0      0      0    8.0500           0         1           0   
414       1  39.0      0      0  108.9000           1         0           1   
415       3  38.5      0      0    7.2500           0         1           0   
416       3  24.0      0      0    8.0500           0         1           0   
417       3  24.0      1      1   22.3583           0         1           1   

     Embarked_Q  Embarked_S  
0             1           0  
1             0           1  
2             1           0  
3             0           1  
4             0           1  
..          ...         ...  
413           0           1  
414           0           0  
415           0           1  
416           0           1  
417           0           0  

[418 rows x 10 columns]

In [103]:
train.head()

Survived  Pclass   Age  SibSp  Parch     Fare  Sex_female  Sex_male  \
0         0       3  22.0      1      0   7.2500           0         1   
1         1       1  38.0      1      0  71.2833           1         0   
2         1       3  26.0      0      0   7.9250           1         0   
3         1       1  35.0      1      0  53.1000           1         0   
4         0       3  35.0      0      0   8.0500           0         1   

   Embarked_C  Embarked_Q  Embarked_S  
0           0           0           1  
1           1           0           0  
2           0           0           1  
3           0           0           1  
4           0           0           1

In [104]:
predictions = model.predict(test)
predictions

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [105]:
test1=pd.read_csv("https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_2/main/%D0%92%D0%B5%D1%81%D0%B5%D0%BD%D0%BD%D0%B8%D0%B9%20%D1%81%D0%B5%D0%BC%D0%B5%D1%81%D1%82%D1%80/class_work_2_log_reg/test.csv")

In [113]:
from google.colab import files #позволяет с локального компьютера загрузить в колаб какие то файлы
final_prediction = pd.DataFrame({'PassengerId':test1['PassengerId'],'Survived':predictions})

final_prediction.to_csv('final_prediction.csv', index=False)

files.download("final_prediction.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>