Задача 2

In [1]:
from IPython.core.interactiveshell import no_op
import numpy as np
n=int(input())
a=float(input())
d=float(input())
def asd(n,a,d):
  b=np.zeros((n,n))
  for i in range(n):
    b[i][i]=a+d*i
  return b
print(asd(n,a,d))


10
2
3
[[ 2.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  5.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  8.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 11.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 14.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 17.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 20.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 23.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 26.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 29.]]


Задача 1

In [5]:
a=str(input())
b=str(input())
y1=int(a[0:4])
m1=int(a[5:7])
d1=int(a[8:10])
y2=int(b[0:4])
m2=int(b[5:7])
d2=int(b[8:10])
t=[]
def daf(a,b):
  y1=int(a[0:4])
  m1=int(a[5:7])
  d1=int(a[8:10])
  y2=int(b[0:4])
  m2=int(b[5:7])
  d2=int(b[8:10])
  for i in range(y1,y1):
    for j in range(m1,13):
      if j==6 and j==4 and j==9 and j==11:
        for k in range(d1,32):
          if j==6 and k==31 and j==4 and j==9 and j==11:
          continue
        elif j==2 and k>=29:
          continue
        if j<10 and k<10:
            p=str(y1)+"-0"+str(j)+"-0"+str(k)
            t.append(p)
        elif j<10 and k>=10:
            p=str(y1)+"-0"+str(j)+"-"+str(k)
            t.append(p)
        elif k<10 and j>=10:
          p=str(y1)+"-"+str(j)+"-0"+str(k)
          t.append(p)




  for i in range(y1,y1):
    for j in range(m1,13):
      for k in range(d1,32):
        if j==6 and k==31 and j==4 and j==9 and j==11:
          continue
        elif j==2 and k>=29:
          continue
        if j<10 and k<10:
            p=str(y1)+"-0"+str(j)+"-0"+str(k)
            t.append(p)
        elif j<10 and k>=10:
            p=str(y1)+"-0"+str(j)+"-"+str(k)
            t.append(p)
        elif k<10 and j>=10:
          p=str(y1)+"-"+str(j)+"-0"+str(k)
          t.append(p)
  for i in range(y1,y1):
    for j in range(m1+1,13):
      for k in range(1,32):
          if j==6 and k==31 and j==4 and j==9 and j==11:
              continue
          elif j==2 and k>=29:
              continue
          if j<10 and k<10:
              p=str(y1)+"-0"+str(j)+"-0"+str(k)
              t.append(p)
          elif j<10 and k>=10:
              p=str(y1)+"-0"+str(j)+"-"+str(k)
              t.append(p)
          elif k<10 and j>=10:
              p=str(y1)+"-"+str(j)+"-0"+str(k)
              t.append(p)
  for i in range(y1,y2):
      for j in range(1,13):
          for k in range(1,32):
            if j==6 and k==31 and j==4 and j==9 and j==11:
                continue
            elif j==2 and k>=29:
                continue
            if j<10 and k<10:
                p=str(y1)+"-0"+str(j)+"-0"+str(k)
                t.append(p)
            elif j<10 and k>=10:
                p=str(y1)+"-0"+str(j)+"-"+str(k)
                t.append(p)
            elif k<10 and j>=10:
                p=str(y1)+"-"+str(j)+"-0"+str(k)
                t.append(p)
  for i in range(y2-1,y2):
      for j in range(1,m2):
        for k in range(1,d2):
            if j==6 and k==31 and j==4 and j==9 and j==11:
                continue
            elif j==2 and k>=29:
                continue
            if j<10 and k<10:
                p=str(y1)+"-0"+str(j)+"-0"+str(k)
                t.append(p)
            elif j<10 and k>=10:
                p=str(y1)+"-0"+str(j)+"-"+str(k)
                t.append(p)
            elif k<10 and j>=10:
                p=str(y1)+"-"+str(j)+"-0"+str(k)
                t.append(p)
  return t

print(daf(a,b))

2005-01-23
2009-06-77
['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04', '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08', '2005-01-09', '2005-01-10', '2005-01-11', '2005-01-12', '2005-01-13', '2005-01-14', '2005-01-15', '2005-01-16', '2005-01-17', '2005-01-18', '2005-01-19', '2005-01-20', '2005-01-21', '2005-01-22', '2005-01-23', '2005-01-24', '2005-01-25', '2005-01-26', '2005-01-27', '2005-01-28', '2005-01-29', '2005-01-30', '2005-01-31', '2005-02-01', '2005-02-02', '2005-02-03', '2005-02-04', '2005-02-05', '2005-02-06', '2005-02-07', '2005-02-08', '2005-02-09', '2005-02-10', '2005-02-11', '2005-02-12', '2005-02-13', '2005-02-14', '2005-02-15', '2005-02-16', '2005-02-17', '2005-02-18', '2005-02-19', '2005-02-20', '2005-02-21', '2005-02-22', '2005-02-23', '2005-02-24', '2005-02-25', '2005-02-26', '2005-02-27', '2005-02-28', '2005-03-01', '2005-03-02', '2005-03-03', '2005-03-04', '2005-03-05', '2005-03-06', '2005-03-07', '2005-03-08', '2005-03-09', '2005-03-10', '2005-03-11

Задача 3

In [10]:
b=np.asarray(list(input()))

def prop(a):
  c=0
  for i in range(len(a)):
    if a[i]==" ":
      a[i]=input()
      c+=1
  return c
print(prop(b))


77 7 8
1 3
3
2
