# Вариант 1.

Кто делает:
1. Александров Данила Александрович
2. Быков Дмитрий Александрович 
3. Горбунов Сергей Михайлович 
4. Горячко Дарья Романовна 
5. Громов Алексей Игоревич
6. Ивлиев Степан Дмитриевич

**Задача 1.**

**1-я входная строка** - год (опционально месяц и день) в формате ISO начала отсчёта.

**2-я входная строка** - год (опционально месяц и день) в формате ISO окончания отсчёта.

Создайте функцию, которая принимает на вход два введенных года и возвращает список (numpy array) дат с шагом в 1 день от начала до окончания отсчёта (последний день не включается).

Результат должен представлять из себя список дат в формате ISO.
Пример - 2005-02-25, где

- 2005 - год
- 02 - месяц
- 25 - день

In [ ]:
# ваше решение

**Задача 2.**

Используя numpy:

Создайте функцию, которая принимает как аргументы целое число N и первый элемент (вещественное число el1), и разность (вещественное число d) и создает матрицу по диагонали, которой распологаются первые N членов арифметической прогрессии.

In [ ]:
# ваше решение

**Задача 3.**

Дан массив. Создайте функцию, которая принимает данный массив и проверяет наличие пропусков и возвращает их количество:
- если есть пропуски, то функция должна их заполнить теми значениями, которые пользователь вводит с клавиатуры.
- если нет пропусков, то функция возвращает 0.

*Встроенные функции заполнения пропусков использовать запрещено.*

In [ ]:
# ваше решение

**Задача 4.**

Вам дан массив, содержащий категории некоторого объекта в виде строк.

Создайте функцию, которая принимает на вход массив, хранящий категории объектов и возвращает:
- закодированный список из чисел, где каждому числу соответсвует какая-то категория;
- число категорий;
- словарь кодирования;

**Например:**

Ввод:

`('red', 'green', 'red', 'blue')`

Вывод:
```(0, 1, 0, 2)
Количество категорий: 3
Словарь кодирования: 
{'red': 0, 'green': 1, 'blue': 2'}
```

*P.s. встроенными функциями кодирования пользоваться запрещено.*

In [ ]:
# ваше решение

# Вариант 2.

Кто делает:
1. Игнатов Константин Дмитриевич
2. Казанов Амир Ринатович
3. Клячин Иван Николаевич
4. Котов Александр Андреевич
5. Мелешкин Кирилл Андреевич
6. Морозов Максим Олегович

**Задача 1.**

На вход подаются 3 числа (каждое с новой строки):

- start
- stop
- n

Создайте функцию, которая принимает 3 введеных числа и возвращает список (numpy.array) из n точек на отрезке (start, stop), попарно равноудалённых друг от друга и от концов отрезка (т.е. разделите отрезок на n+1 часть). Округлите значения точек до 3 знака после запятой.

In [ ]:
# ваше решение

**Задача 2.**

Дан массив размерностью NxM.

Напишите функцию, которая нормализует все элементы матрицы.

**Немного теории.** *Нормализацией данных называется приведение их к некоторой общей шкале без потери информации о различии диапазонов.*

*Новые значения элементов расчитываются как:*

$x' = \frac{x-x_{min}}{x_{max}-x_{min}}$

In [ ]:
# ваше решение

**Задача 3.**

Вам дан одномерный массив. Напишите функцию, которая принимает этот массив и возвращает:
1. Количество локальных максимумов для этого массива;
2. И сами эти максимумы.

*P.s. встроенными функциями пользоваться запрещено.*

In [ ]:
# ваше решение

**Задача 4.**

Реализуйте функцию умножения двух матриц, без использования встроенной функции.

In [ ]:
# ваше решение

# Вариант 3.

Кто делает:

1. Переттруов Никита Артемович
2. Пославский Егор Константинович
3. Садохин Константин Павлович
4. Скиданов Дмитрий Артёмович
5. Судариков Андрей Геннадьевич
6. Таланов Максим Андреевич

**Задача 1.**

На вход подаются 3 числа (каждое с новой строки):

- start
- stop
- n

Создайте функцию, которая возвращает список из n точек на отрезке [start, stop] в геометрической прогрессии, включая start и stop.

Округлите значения точек до 3 знака после запятой.

In [ ]:
import numpy as np
def count(start,stop,n):
    i = 0
    y = stop / start
    x = y ** (1 / (n - 1))
    while i != n:
        print(round(start, 3))
        start = start * x
        i += 1
    return x

start = int(input())
stop = int(input())
n = int(input())
print (count(start,stop,n))

**Задача 2.**

Дана матрица. Напишите функцию, которая принимает в качестве аргумента данную матрицу и возврщает транспонированную матрицу.

**Немного теории**. *Транспонированной матрицей $A^T$ называется матрица, полученная из исходной матрицы $A$ заменой строк на столбцы. Формально: элементы матрицы $A^T$ определяются как ${a^T}_{ij} = a_{ji}$, где ${a^T}_{ij}$ — элемент матрицы $A^T$, стоящий на пересечении строки с номером $i$ и столбца с номером $j$.*

P.s. использовать встроенные функции Numpy для транспонирования запрещено.

In [ ]:
def trans(x):
    y = [list(z) for z in list(zip(*x))]
    return(y)
x = [[1,2,3,4], [5,6,7,8,], [9,10,11,12]]
print(trans(x))

**Задача 3.**

Даны два массива A и B формы (8,3) и (2,2). 
Напишите фукнкцию, которая возвращает строки A, содержащие элементы каждой строки B, независимо от порядка элементов в B?

**Задача 4.**

Дан вектор. Реализуйте функцию, которая возвращает каждый элемент в двоичном предствалении в виде вектора.

Например:

Ввод:

`[0, 1, 2, 3, 15, 16, 32, 64, 128]`

Вывод:

```
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
 ```

In [ ]:
def zxc(x):
    y = len(x)
    n = 0
    k = 0
    while k != y:
        z = []
        c = x[k] + 1
        while (c - 2 ** n) > 0:
            n += 1
        while n > -1:
            if c - 2 ** n > 0:
                c = c - 2 ** n
                z.append(1)
            else:
                z.append(0)
            n -= 1
        k += 1
        print(z[1:])
x = [1, 3, 4, 5]
print (zxc(x))

# Вариант 4.

Кто делает:
1. Игнатов Игорь Дмитриевич
2. Файзуллин Илья Денисович
3. Чупрова Ася Александровна
4. Ямпольская Ирина Вадимовна
5. Дидковский Илья Радионович

**Задача 1.**

Реализовать функцию, которая принимает матрицу 3x3 и возвращает обратную по отношеную к ней матрицу.

**Немного теории**. *Матрица $А^{-1}$ называется обратной матрицей по отношению к матрице $А$, если $А*А^{-1} = Е$, где $Е$ — единичная матрица n-го порядка. Обратная матрица может существовать только для квадратных матриц.*

P.s. использовать встроенные функции запрещено.

In [ ]:
# ваше решение

**Задача 2.**

Дан одномернный массив. Создайте функцию, которая принимает данные массив и возвращает массив, состоящий из элементов, целая часть от деления которых больше 3.

In [ ]:
# ваше решение

**Задача 3.**

Дана матрица 4х3 (содержащаяя координаты 4х векторов, столбцы это соотсветсвенно x,y,z) и вектор (x,y,z). Напишите функцию которая возвращает ближащий вектор из матрицы к заданому вектору (согласно расстоянию между векторами).

In [ ]:
# ваше решение

**Задача 4.**

Дан вектор из ненулевых элементов. Вставьте между каждыми элементами по три 0.

In [ ]:
# ваше решение