Задача 2

In [10]:
from IPython.core.interactiveshell import no_op
import numpy as np 
n=int(input())
a=float(input())
d=float(input())
b=np.zeros((n,n))
for i in range(n):
  b[i][i]=a+d*i
print(b)


10
2
3
[[ 2.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  5.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  8.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 11.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 14.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 17.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 20.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 23.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 26.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 29.]]


Задача 1

In [ ]:
a=str(input())
b=str(input())
y1=int(a[0:4])
m1=int(a[5:7])
d1=int(a[8:10])
y2=int(b[0:4])
m2=int(b[5:7])
d2=int(b[8:10])
t=[]
for i in range(y1,y1):
    for j in range(m1,m1):
        for k in range(d1,32):
            if j==6 and k==31 and j==4 and j==9 and j==11:
                continue
            elif j==2 and k>=29:
                continue
            if j<10 and k<10:
                p=str(y1)+"-0"+str(j)+"-0"+str(k)
                t.append(p)
            elif j<10 and k>=10:
                p=str(y1)+"-0"+str(j)+"-"+str(k)
                t.append(p)
            elif k<10 and j>=10:
                p=str(y1)+"-"+str(j)+"-0"+str(k)
                t.append(p)
for i in range(y1,y1):
    for j in range(m1+1,13):
        for k in range(1,32):
            if j==6 and k==31 and j==4 and j==9 and j==11:
                continue
            elif j==2 and k>=29:
                continue
            if j<10 and k<10:
                p=str(y1)+"-0"+str(j)+"-0"+str(k)
                t.append(p)
            elif j<10 and k>=10:
                p=str(y1)+"-0"+str(j)+"-"+str(k)
                t.append(p)
            elif k<10 and j>=10:
                p=str(y1)+"-"+str(j)+"-0"+str(k)
                t.append(p)
for i in range(y1+1,y2):
    for j in range(1,13):
        for k in range(1,32):
            if j==6 and k==31 and j==4 and j==9 and j==11:
                continue
            elif j==2 and k>=29:
                continue
            if j<10 and k<10:
                p=str(y1)+"-0"+str(j)+"-0"+str(k)
                t.append(p)
            elif j<10 and k>=10:
                p=str(y1)+"-0"+str(j)+"-"+str(k)
                t.append(p)
            elif k<10 and j>=10:
                p=str(y1)+"-"+str(j)+"-0"+str(k)
                t.append(p)
for i in range(y2-1,y2):
    for j in range(1,m2):
        for k in range(1,d2):
            if j==6 and k==31 and j==4 and j==9 and j==11:
                continue
            elif j==2 and k>=29:
                continue
            if j<10 and k<10:
                p=str(y1)+"-0"+str(j)+"-0"+str(k)
                t.append(p)
            elif j<10 and k>=10:
                p=str(y1)+"-0"+str(j)+"-"+str(k)
                t.append(p)
            elif k<10 and j>=10:
                p=str(y1)+"-"+str(j)+"-0"+str(k)
                t.append(p)

print(t)

Задача 3

In [8]:
c=0
a=np.asarray(input())
for i in range(len(a)):
  if a[i]==" ":
    a[i]=input()
    c+=1
print(c)


KeyboardInterrupt: ignored