# Вариант 2.

Кто делает:
1. Игнатов Константин Дмитриевич
2. Казанов Амир Ринатович
3. Клячин Иван Николаевич
4. Котов Александр Андреевич
5. Мелешкин Кирилл Андреевич
6. Морозов Максим Олегович

**Задача 1.**

На вход подаются 3 числа (каждое с новой строки):

- start
- stop
- n

Создайте функцию, которая принимает 3 введеных числа и возвращает список (numpy.array) из n точек на отрезке (start, stop), попарно равноудалённых друг от друга и от концов отрезка (т.е. разделите отрезок на n+1 часть). Округлите значения точек до 3 знака после запятой.

In [32]:
from numpy import *
a = float(input())
b = float(input())
c = int(input())

def arLine(strt, stp, n):
  ln = stp - strt
  ar = array([round(strt + i*ln/n, 3) for i in range(n+1)], float)
  return ar

print(arLine(a,b,c))

3.5642
18.54711
9
[ 3.564  5.229  6.894  8.559 10.223 11.888 13.553 15.218 16.882 18.547]


**Задача 2.**

Дан массив размерностью NxM.

Напишите функцию, которая нормализует все элементы матрицы.

**Немного теории.** *Нормализацией данных называется приведение их к некоторой общей шкале без потери информации о различии диапазонов.*

*Новые значения элементов расчитываются как:*

$x' = \frac{x-x_{min}}{x_{max}-x_{min}}$

In [29]:
from numpy import *
ar = array([[4 , 7 , 6],[1, -8, 5],[2.54, 6.11, 9]], float)

def nrmMtrx(m):
    m = (m-m.min())/(m.max()-m.min())
    return m

print(nrmMtrx(ar))

[[0.70588235 0.88235294 0.82352941]
 [0.52941176 0.         0.76470588]
 [0.62       0.83       1.        ]]


**Задача 3.**

Вам дан одномерный массив. Напишите функцию, которая принимает этот массив и возвращает:
1. Количество локальных максимумов для этого массива;
2. И сами эти максимумы.

*P.s. встроенными функциями пользоваться запрещено.*

In [18]:
from numpy import *
ar = array(list(map(float, input().split())), float)

def maxAr(x):
    cnt = 0
    a = []

    for i in range(1, len(x)-1):
      if x[i] > x[i-1] and x[i] > x[i+1]:
        cnt += 1
        a.append(x[i])
    return cnt, a

maxAr(ar)

2 8 6 5 3 10 122 20 213 16 1287  23176823 16213 7214712476


(4, [8.0, 122.0, 213.0, 23176823.0])

**Задача 4.**

Реализуйте функцию умножения двух матриц, без использования встроенной функции.

In [43]:
from numpy import *

mtrx1 = array([[1, 62.42, 12.6, 7], [3, 4, 21.5, 8]], float)
mtrx2 = array([[9, 1.32], [3, 4], [1, 9], [5, 0.4]], float)

def mtrxMltp(m1, m2):
    a = zeros((m1.shape[0], m2.shape[1]))
    z = m2.flatten()
    for i in range(m1.shape[0]):
      for j in range(m2.shape[1]):
        a[i,j] = sum(m1[i] * z[j::m2.shape[1]])


    return a

print(mtrxMltp(mtrx2, mtrx1), '\n\n')
print(dot(mtrx2, mtrx1))

[[ 12.96 567.06 141.78  73.56]
 [ 15.   203.26 123.8   53.  ]
 [ 28.    98.42 206.1   79.  ]
 [  6.2  313.7   71.6   38.2 ]] 


[[ 12.96 567.06 141.78  73.56]
 [ 15.   203.26 123.8   53.  ]
 [ 28.    98.42 206.1   79.  ]
 [  6.2  313.7   71.6   38.2 ]]
