# Вариант 1.

Кто делает:
1. Александров Данила Александрович
2. Быков Дмитрий Александрович 
3. Горбунов Сергей Михайлович 
4. Горячко Дарья Романовна 
5. Громов Алексей Игоревич
6. Ивлиев Степан Дмитриевич

**Задача 1.**

**1-я входная строка** - год (опционально месяц и день) в формате ISO начала отсчёта.

**2-я входная строка** - год (опционально месяц и день) в формате ISO окончания отсчёта.

Создайте функцию, которая принимает на вход два введенных года и возвращает список (numpy array) дат с шагом в 1 день от начала до окончания отсчёта (последний день не включается).

Результат должен представлять из себя список дат в формате ISO.
Пример - 2005-02-25, где

- 2005 - год
- 02 - месяц
- 25 - день

In [3]:

from datetime import date, timedelta

d1 = date(2019, 8, 13)  
d2 = date(2020, 9, 13)  

delta = d2 - d1         
for i in range(delta.days + 1):
    print(d1 + timedelta(i))

2019-08-13
2019-08-14
2019-08-15
2019-08-16
2019-08-17
2019-08-18
2019-08-19
2019-08-20
2019-08-21
2019-08-22
2019-08-23
2019-08-24
2019-08-25
2019-08-26
2019-08-27
2019-08-28
2019-08-29
2019-08-30
2019-08-31
2019-09-01
2019-09-02
2019-09-03
2019-09-04
2019-09-05
2019-09-06
2019-09-07
2019-09-08
2019-09-09
2019-09-10
2019-09-11
2019-09-12
2019-09-13
2019-09-14
2019-09-15
2019-09-16
2019-09-17
2019-09-18
2019-09-19
2019-09-20
2019-09-21
2019-09-22
2019-09-23
2019-09-24
2019-09-25
2019-09-26
2019-09-27
2019-09-28
2019-09-29
2019-09-30
2019-10-01
2019-10-02
2019-10-03
2019-10-04
2019-10-05
2019-10-06
2019-10-07
2019-10-08
2019-10-09
2019-10-10
2019-10-11
2019-10-12
2019-10-13
2019-10-14
2019-10-15
2019-10-16
2019-10-17
2019-10-18
2019-10-19
2019-10-20
2019-10-21
2019-10-22
2019-10-23
2019-10-24
2019-10-25
2019-10-26
2019-10-27
2019-10-28
2019-10-29
2019-10-30
2019-10-31
2019-11-01
2019-11-02
2019-11-03
2019-11-04
2019-11-05
2019-11-06
2019-11-07
2019-11-08
2019-11-09
2019-11-10
2019-11-11

**Задача 2.**

Используя numpy:

Создайте функцию, которая принимает как аргументы целое число N и первый элемент (вещественное число el1), и разность (вещественное число d) и создает матрицу по диагонали, которой распологаются первые N членов арифметической прогрессии.

In [5]:
!pip install numpy
import numpy  as np
n=int(input())
el1=float(input())
d=float(input())

arr = np.diag(np.arange(el1, el1 + d*n, d))
print(arr)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
5
4
5.5
[[ 4.   0.   0.   0.   0. ]
 [ 0.   9.5  0.   0.   0. ]
 [ 0.   0.  15.   0.   0. ]
 [ 0.   0.   0.  20.5  0. ]
 [ 0.   0.   0.   0.  26. ]]


**Задача 3.**

Дан массив. Создайте функцию, которая принимает данный массив и проверяет наличие пропусков и возвращает их количество:
- если есть пропуски, то функция должна их заполнить теми значениями, которые пользователь вводит с клавиатуры.
- если нет пропусков, то функция возвращает 0.

*Встроенные функции заполнения пропусков использовать запрещено.*

In [4]:
import numpy as np
a = np.array([1, np.NaN, 5], float)
b=int(input()) 
def f():
  global a
  res = 0
  for i in range(a.shape[0]):
    if np.isnan(a[i]):
      a[i] = b
      res += 1
  return res
 
print(f())
a

3
1


array([1., 3., 5.])

**Задача 4.**

Вам дан массив, содержащий категории некоторого объекта в виде строк.

Создайте функцию, которая принимает на вход массив, хранящий категории объектов и возвращает:
- закодированный список из чисел, где каждому числу соответсвует какая-то категория;
- число категорий;
- словарь кодирования;

**Например:**

Ввод:

`('red', 'green', 'red', 'blue')`

Вывод:
```(0, 1, 0, 2)
Количество категорий: 3
Словарь кодирования: 
{'red': 0, 'green': 1, 'blue': 2'}
```

*P.s. встроенными функциями кодирования пользоваться запрещено.*

In [ ]:
!pip install numpy
import numpy  as np
c=0
s=0
a = np.array(('red', 'green', 'red', 'blue'), float)
num = [0, 1, 0, 2]
a_dictionary = dict(zip(a, num))
for i in num:
  num[c]=b
  if b==num[i]:
    s+=1
    c+=1
    



# Вариант 2.

Кто делает:
1. Игнатов Константин Дмитриевич
2. Казанов Амир Ринатович
3. Клячин Иван Николаевич
4. Котов Александр Андреевич
5. Мелешкин Кирилл Андреевич
6. Морозов Максим Олегович

**Задача 1.**

На вход подаются 3 числа (каждое с новой строки):

- start
- stop
- n

Создайте функцию, которая принимает 3 введеных числа и возвращает список (numpy.array) из n точек на отрезке (start, stop), попарно равноудалённых друг от друга и от концов отрезка (т.е. разделите отрезок на n+1 часть). Округлите значения точек до 3 знака после запятой.

In [ ]:
# ваше решение

**Задача 2.**

Дан массив размерностью NxM.

Напишите функцию, которая нормализует все элементы матрицы.

**Немного теории.** *Нормализацией данных называется приведение их к некоторой общей шкале без потери информации о различии диапазонов.*

*Новые значения элементов расчитываются как:*

$x' = \frac{x-x_{min}}{x_{max}-x_{min}}$

In [ ]:
# ваше решение

**Задача 3.**

Вам дан одномерный массив. Напишите функцию, которая принимает этот массив и возвращает:
1. Количество локальных максимумов для этого массива;
2. И сами эти максимумы.

*P.s. встроенными функциями пользоваться запрещено.*

In [ ]:
# ваше решение

**Задача 4.**

Реализуйте функцию умножения двух матриц, без использования встроенной функции.

In [ ]:
# ваше решение

# Вариант 3.

Кто делает:

1. Переттруов Никита Артемович
2. Пославский Егор Константинович
3. Садохин Константин Павлович
4. Скиданов Дмитрий Артёмович
5. Судариков Андрей Геннадьевич
6. Таланов Максим Андреевич

**Задача 1.**

На вход подаются 3 числа (каждое с новой строки):

- start
- stop
- n

Создайте функцию, которая возвращает список из n точек на отрезке [start, stop] в геометрической прогрессии, включая start и stop.

Округлите значения точек до 3 знака после запятой.

In [ ]:
# ваше решение

**Задача 2.**

Дана матрица. Напишите функцию, которая принимает в качестве аргумента данную матрицу и возврщает транспонированную матрицу.

**Немного теории**. *Транспонированной матрицей $A^T$ называется матрица, полученная из исходной матрицы $A$ заменой строк на столбцы. Формально: элементы матрицы $A^T$ определяются как ${a^T}_{ij} = a_{ji}$, где ${a^T}_{ij}$ — элемент матрицы $A^T$, стоящий на пересечении строки с номером $i$ и столбца с номером $j$.*

P.s. использовать встроенные функции Numpy для транспонирования запрещено.

In [ ]:
# ваше решение

**Задача 3.**

Даны два массива A и B формы (8,3) и (2,2). 
Напишите фукнкцию, которая возвращает строки A, содержащие элементы каждой строки B, независимо от порядка элементов в B?

In [ ]:
# ваше решение

**Задача 4.**

Дан вектор. Реализуйте функцию, которая возвращает каждый элемент в двоичном предствалении в виде вектора.

Например:

Ввод:

`[0, 1, 2, 3, 15, 16, 32, 64, 128]`

Вывод:

```
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
 ```

In [ ]:
# ваше решение

# Вариант 4.

Кто делает:
1. Игнатов Игорь Дмитриевич
2. Файзуллин Илья Денисович
3. Чупрова Ася Александровна
4. Ямпольская Ирина Вадимовна
5. Дидковский Илья Радионович

**Задача 1.**

Реализовать функцию, которая принимает матрицу 3x3 и возвращает обратную по отношеную к ней матрицу.

**Немного теории**. *Матрица $А^{-1}$ называется обратной матрицей по отношению к матрице $А$, если $А*А^{-1} = Е$, где $Е$ — единичная матрица n-го порядка. Обратная матрица может существовать только для квадратных матриц.*

P.s. использовать встроенные функции запрещено.

In [ ]:
# ваше решение

**Задача 2.**

Дан одномернный массив. Создайте функцию, которая принимает данные массив и возвращает массив, состоящий из элементов, целая часть от деления которых больше 3.

In [ ]:
# ваше решение

**Задача 3.**

Дана матрица 4х3 (содержащаяя координаты 4х векторов, столбцы это соотсветсвенно x,y,z) и вектор (x,y,z). Напишите функцию которая возвращает ближащий вектор из матрицы к заданому вектору (согласно расстоянию между векторами).

In [ ]:
# ваше решение

**Задача 4.**

Дан вектор из ненулевых элементов. Вставьте между каждыми элементами по три 0.

In [ ]:
# ваше решение