# Вариант 1.

Кто делает:
1. Александров Данила Александрович
2. Быков Дмитрий Александрович 
3. Горбунов Сергей Михайлович 
4. Горячко Дарья Романовна 
5. Громов Алексей Игоревич
6. Ивлиев Степан Дмитриевич

**Задача 1.**

**1-я входная строка** - год (опционально месяц и день) в формате ISO начала отсчёта.

**2-я входная строка** - год (опционально месяц и день) в формате ISO окончания отсчёта.

Создайте функцию, которая принимает на вход два введенных года и возвращает список (numpy array) дат с шагом в 1 день от начала до окончания отсчёта (последний день не включается).

Результат должен представлять из себя список дат в формате ISO.
Пример - 2005-02-25, где

- 2005 - год
- 02 - месяц
- 25 - день

In [4]:
# ваше решение
import numpy as np
def correct_output(out):
  return out if out >= 10 else '0' + str(out)
  
def result(year_1, year_2):
  res = []
  month = 0
  for year in range(year_1, year_2):
    for month in range(1, 12 + 1):
      for date in range(1, 31 + 1):
        res.append(f"{year}-{ correct_output(month) }-{ correct_output(date) }")
  return res

year_1 = int(input())
year_2 = int(input())

result(year_1, year_2)

2022
2023


['2022-01-01',
 '2022-01-02',
 '2022-01-03',
 '2022-01-04',
 '2022-01-05',
 '2022-01-06',
 '2022-01-07',
 '2022-01-08',
 '2022-01-09',
 '2022-01-10',
 '2022-01-11',
 '2022-01-12',
 '2022-01-13',
 '2022-01-14',
 '2022-01-15',
 '2022-01-16',
 '2022-01-17',
 '2022-01-18',
 '2022-01-19',
 '2022-01-20',
 '2022-01-21',
 '2022-01-22',
 '2022-01-23',
 '2022-01-24',
 '2022-01-25',
 '2022-01-26',
 '2022-01-27',
 '2022-01-28',
 '2022-01-29',
 '2022-01-30',
 '2022-01-31',
 '2022-02-01',
 '2022-02-02',
 '2022-02-03',
 '2022-02-04',
 '2022-02-05',
 '2022-02-06',
 '2022-02-07',
 '2022-02-08',
 '2022-02-09',
 '2022-02-10',
 '2022-02-11',
 '2022-02-12',
 '2022-02-13',
 '2022-02-14',
 '2022-02-15',
 '2022-02-16',
 '2022-02-17',
 '2022-02-18',
 '2022-02-19',
 '2022-02-20',
 '2022-02-21',
 '2022-02-22',
 '2022-02-23',
 '2022-02-24',
 '2022-02-25',
 '2022-02-26',
 '2022-02-27',
 '2022-02-28',
 '2022-02-29',
 '2022-02-30',
 '2022-02-31',
 '2022-03-01',
 '2022-03-02',
 '2022-03-03',
 '2022-03-04',
 '2022-03-

**Задача 2.**

Используя numpy:

Создайте функцию, которая принимает как аргументы целое число N и первый элемент (вещественное число el1), и разность (вещественное число d) и создает матрицу по диагонали, которой распологаются первые N членов арифметической прогрессии.

In [7]:
# ваше решение
import numpy as np
n=int(input())
el1=float(input())
d = float(input())
arr = np.diag(np.arange(el1, el1 + d*n, d))
print(arr)

15
1
1
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  4.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  5.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  6.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  7.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  8.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  9.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 12.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 13.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 14.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 15.]]


**Задача 3.**

Дан массив. Создайте функцию, которая принимает данный массив и проверяет наличие пропусков и возвращает их количество:
- если есть пропуски, то функция должна их заполнить теми значениями, которые пользователь вводит с клавиатуры.
- если нет пропусков, то функция возвращает 0.

*Встроенные функции заполнения пропусков использовать запрещено.*

In [ ]:
# ваше решение

**Задача 4.**

Вам дан массив, содержащий категории некоторого объекта в виде строк.

Создайте функцию, которая принимает на вход массив, хранящий категории объектов и возвращает:
- закодированный список из чисел, где каждому числу соответсвует какая-то категория;
- число категорий;
- словарь кодирования;

**Например:**

Ввод:

`('red', 'green', 'red', 'blue')`

Вывод:
```(0, 1, 0, 2)
Количество категорий: 3
Словарь кодирования: 
{'red': 0, 'green': 1, 'blue': 2'}
```

*P.s. встроенными функциями кодирования пользоваться запрещено.*

In [ ]:
# ваше решение

# Вариант 2.

Кто делает:
1. Игнатов Константин Дмитриевич
2. Казанов Амир Ринатович
3. Клячин Иван Николаевич
4. Котов Александр Андреевич
5. Мелешкин Кирилл Андреевич
6. Морозов Максим Олегович

**Задача 1.**

На вход подаются 3 числа (каждое с новой строки):

- start
- stop
- n

Создайте функцию, которая принимает 3 введеных числа и возвращает список (numpy.array) из n точек на отрезке (start, stop), попарно равноудалённых друг от друга и от концов отрезка (т.е. разделите отрезок на n+1 часть). Округлите значения точек до 3 знака после запятой.

In [ ]:
# ваше решение

**Задача 2.**

Дан массив размерностью NxM.

Напишите функцию, которая нормализует все элементы матрицы.

**Немного теории.** *Нормализацией данных называется приведение их к некоторой общей шкале без потери информации о различии диапазонов.*

*Новые значения элементов расчитываются как:*

$x' = \frac{x-x_{min}}{x_{max}-x_{min}}$

In [ ]:
# ваше решение

**Задача 3.**

Вам дан одномерный массив. Напишите функцию, которая принимает этот массив и возвращает:
1. Количество локальных максимумов для этого массива;
2. И сами эти максимумы.

*P.s. встроенными функциями пользоваться запрещено.*

In [ ]:
# ваше решение

**Задача 4.**

Реализуйте функцию умножения двух матриц, без использования встроенной функции.

In [ ]:
# ваше решение

# Вариант 3.

Кто делает:

1. Переттруов Никита Артемович
2. Пославский Егор Константинович
3. Садохин Константин Павлович
4. Скиданов Дмитрий Артёмович
5. Судариков Андрей Геннадьевич
6. Таланов Максим Андреевич

**Задача 1.**

На вход подаются 3 числа (каждое с новой строки):

- start
- stop
- n

Создайте функцию, которая возвращает список из n точек на отрезке [start, stop] в геометрической прогрессии, включая start и stop.

Округлите значения точек до 3 знака после запятой.

In [ ]:
# ваше решение

**Задача 2.**

Дана матрица. Напишите функцию, которая принимает в качестве аргумента данную матрицу и возврщает транспонированную матрицу.

**Немного теории**. *Транспонированной матрицей $A^T$ называется матрица, полученная из исходной матрицы $A$ заменой строк на столбцы. Формально: элементы матрицы $A^T$ определяются как ${a^T}_{ij} = a_{ji}$, где ${a^T}_{ij}$ — элемент матрицы $A^T$, стоящий на пересечении строки с номером $i$ и столбца с номером $j$.*

P.s. использовать встроенные функции Numpy для транспонирования запрещено.

In [ ]:
# ваше решение

**Задача 3.**

Даны два массива A и B формы (8,3) и (2,2). 
Напишите фукнкцию, которая возвращает строки A, содержащие элементы каждой строки B, независимо от порядка элементов в B?

In [ ]:
# ваше решение

**Задача 4.**

Дан вектор. Реализуйте функцию, которая возвращает каждый элемент в двоичном предствалении в виде вектора.

Например:

Ввод:

`[0, 1, 2, 3, 15, 16, 32, 64, 128]`

Вывод:

```
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
 ```

In [ ]:
# ваше решение

# Вариант 4.

Кто делает:
1. Игнатов Игорь Дмитриевич
2. Файзуллин Илья Денисович
3. Чупрова Ася Александровна
4. Ямпольская Ирина Вадимовна
5. Дидковский Илья Радионович

**Задача 1.**

Реализовать функцию, которая принимает матрицу 3x3 и возвращает обратную по отношеную к ней матрицу.

**Немного теории**. *Матрица $А^{-1}$ называется обратной матрицей по отношению к матрице $А$, если $А*А^{-1} = Е$, где $Е$ — единичная матрица n-го порядка. Обратная матрица может существовать только для квадратных матриц.*

P.s. использовать встроенные функции запрещено.

In [ ]:
# ваше решение

**Задача 2.**

Дан одномернный массив. Создайте функцию, которая принимает данные массив и возвращает массив, состоящий из элементов, целая часть от деления которых больше 3.

In [ ]:
# ваше решение

**Задача 3.**

Дана матрица 4х3 (содержащаяя координаты 4х векторов, столбцы это соотсветсвенно x,y,z) и вектор (x,y,z). Напишите функцию которая возвращает ближащий вектор из матрицы к заданому вектору (согласно расстоянию между векторами).

In [ ]:
# ваше решение

**Задача 4.**

Дан вектор из ненулевых элементов. Вставьте между каждыми элементами по три 0.

In [ ]:
# ваше решение